### ISSUE TITLE
feature-name and slug differ for all pseudo-classes/elements

### ISSUE THREAD

**Issue by tabatkins** [w3c/mdn-spec-links#2]
The keys used in the bcd data structures are clearly optimized for JS usage, and so non-JS-ident characters, such as `:`, are stripped. They're retained in the actual URLs, tho, which are used to determine the slugs.

As a result, every single pseudo-class and pseudo-element currently triggers the "mismatched between feature name and MDN url" warning in Bikeshed; Selectors in particular is wrecked by this.

I can hack around this in Bikeshed, but since this repo is massaging the data into a flatter format anyway (and thus the feature name doesn't need to correspond to the bcd data structures), maybe we can just fix this here? Specifically, if the only difference between the feature name and the slug name is the presence of `:`, then change the feature name to match the slug name, so they both have `:`.

**Comment by tabatkins** [comment]
Ah, functional pseudos also differ in that their feature name removes the parens, but the slug retains them (for example, `host` feature name vs `:host()` slug). So roll that in too.

**Comment by tabatkins** [comment]
Oh jeez there's just a lot of differences; `:host()` actually has the feature name `hostfunction`.

Stepping back a moment, what's the purpose of this check in the Bikeshed code? What goes wrong if feature name and slug don't match?

**Comment by sideshowbarker** [comment]
> Stepping back a moment, what's the purpose of this check in the Bikeshed code?

The intent was to try to help catch cases where somebody edited the https://github.com/mdn/browser-compat-data data for a feature but put the wrong `mdn_url` value — that is, they associated the feature with the wrong MDN article.

It’s not a hypothetical case — I’ve run into it a number of times — which is why I added the check in the Bikeshed code. In some instances the BCD data seems to have ended up with such cases due to copypasta. In other cases it’s because somebody put in the URL for a similar-looking-but-actually-unrelated interface name, or a member name that’s right but the URL is for a member with the same name in a different interface.

Anyway, that check in Bikeshed isn’t essential — nothing will break in the Bikeshed annotation-behavior with it removed — so the https://github.com/tabatkins/bikeshed/commit/c1dbacabba9018350dc731348d78fcdf9f3b4bd1 removal was the right decision.

In hindsight, Bikeshed isn’t the right place to be trying to do the check anyway; the check should better be getting done upstream (if in fact it’s actually possible to do it at all without getting tons of false positives like the ones you ran into) — as a linting rule that runs whenever somebody makes a BCD patch and raises a PR for it.

**Comment by tabatkins** [comment]
That makes sense, yeah. It's just got way too many false-positives, in CSS at least, to bug people with. Godspeed on figuring out a way to get it checked upstream, tho.

(Having the check, with an allowlist of known exceptions, seems like it would be very doable and useful.)

**Comment by tabatkins** [comment]
I was composing an issue against BCD for this, and tracked down the full list of mismatches:

<details>
<summary>it's big, click to expand</summary>
<pre>
  Mismatch in compat.json: f=-webkit-max-device-pixel-ratio s=-webkit-device-pixel-ratio
  Mismatch in compat.json: f=-webkit-min-device-pixel-ratio s=-webkit-device-pixel-ratio
compat.json total: 2
  Mismatch in css-2.json: f=charset s=@charset
  Mismatch in css-2.json: f=import s=@import
  Mismatch in css-2.json: f=media s=@media
  Mismatch in css-2.json: f=page-margin-boxes s=@page
  Mismatch in css-2.json: f=page s=@page
  Mismatch in css-2.json: f=first s=:first
  Mismatch in css-2.json: f=left s=:left
  Mismatch in css-2.json: f=right s=:right
  Mismatch in css-2.json: f=position s=position_value
  Mismatch in css-2.json: f=active s=:active
  Mismatch in css-2.json: f=focus s=:focus
  Mismatch in css-2.json: f=hover s=:hover
  Mismatch in css-2.json: f=adjacent_sibling s=Adjacent_sibling_combinator
  Mismatch in css-2.json: f=after s=::after
  Mismatch in css-2.json: f=before s=::before
  Mismatch in css-2.json: f=attribute s=Attribute_selectors
  Mismatch in css-2.json: f=child s=Child_combinator
  Mismatch in css-2.json: f=class s=Class_selectors
  Mismatch in css-2.json: f=descendant s=Descendant_combinator
  Mismatch in css-2.json: f=first-child s=:first-child
  Mismatch in css-2.json: f=first-letter s=::first-letter
  Mismatch in css-2.json: f=first-line s=::first-line
  Mismatch in css-2.json: f=id s=ID_selectors
  Mismatch in css-2.json: f=lang s=:lang
  Mismatch in css-2.json: f=link s=:link
  Mismatch in css-2.json: f=visited s=:visited
  Mismatch in css-2.json: f=type s=Type_selectors
  Mismatch in css-2.json: f=universal s=Universal_selectors
  Mismatch in css-2.json: f=color s=color_value
css-2.json total: 29
  Mismatch in css-align-3.json: f=flex_context s=align-content
  Mismatch in css-align-3.json: f=grid_context s=align-content
  Mismatch in css-align-3.json: f=flex_context s=align-items
  Mismatch in css-align-3.json: f=grid_context s=align-items
  Mismatch in css-align-3.json: f=flex_context s=align-self
  Mismatch in css-align-3.json: f=grid_context s=align-self
  Mismatch in css-align-3.json: f=flex_context s=column-gap
  Mismatch in css-align-3.json: f=grid_context s=column-gap
  Mismatch in css-align-3.json: f=multicol_context s=column-gap
  Mismatch in css-align-3.json: f=flex_context s=gap
  Mismatch in css-align-3.json: f=grid_context s=gap
  Mismatch in css-align-3.json: f=multicol_context s=gap
  Mismatch in css-align-3.json: f=flex_context s=justify-content
  Mismatch in css-align-3.json: f=grid_context s=justify-content
  Mismatch in css-align-3.json: f=flex_context s=justify-items
  Mismatch in css-align-3.json: f=grid_context s=justify-items
  Mismatch in css-align-3.json: f=flex_context s=justify-self
  Mismatch in css-align-3.json: f=grid_context s=justify-self
  Mismatch in css-align-3.json: f=flex_context s=place-content
  Mismatch in css-align-3.json: f=grid_context s=place-content
  Mismatch in css-align-3.json: f=flex_context s=place-items
  Mismatch in css-align-3.json: f=grid_context s=place-items
  Mismatch in css-align-3.json: f=flex_context s=place-self
  Mismatch in css-align-3.json: f=grid_context s=place-self
  Mismatch in css-align-3.json: f=flex_context s=row-gap
  Mismatch in css-align-3.json: f=grid_context s=row-gap
css-align-3.json total: 26
  Mismatch in css-animations-1.json: f=keyframes s=@keyframes
css-animations-1.json total: 1
  Mismatch in css-backgrounds-3.json: f=position s=position_value
css-backgrounds-3.json total: 1
  Mismatch in css-break-3.json: f=multicol_context s=break-after
  Mismatch in css-break-3.json: f=paged_context s=break-after
  Mismatch in css-break-3.json: f=region_context s=break-after
  Mismatch in css-break-3.json: f=multicol_context s=break-before
  Mismatch in css-break-3.json: f=paged_context s=break-before
  Mismatch in css-break-3.json: f=region_context s=break-before
  Mismatch in css-break-3.json: f=multicol_context s=break-inside
  Mismatch in css-break-3.json: f=paged_context s=break-inside
  Mismatch in css-break-3.json: f=region_context s=break-inside
css-break-3.json total: 9
  Mismatch in css-cascade-3.json: f=import s=@import
css-cascade-3.json total: 1
  Mismatch in css-cascade-4.json: f=import s=@import
css-cascade-4.json total: 1
  Mismatch in css-color-3.json: f=color s=color_value
css-color-3.json total: 1
  Mismatch in css-color-4.json: f=color s=color_value
css-color-4.json total: 1
  Mismatch in css-conditional-3.json: f=media s=@media
  Mismatch in css-conditional-3.json: f=supports s=@supports
css-conditional-3.json total: 2
  Mismatch in css-conditional-4.json: f=supports s=@supports
css-conditional-4.json total: 1
  Mismatch in css-counter-styles-3.json: f=counter-style s=@counter-style
css-counter-styles-3.json total: 1
  Mismatch in css-device-adapt-1.json: f=viewport s=@viewport
css-device-adapt-1.json total: 1
  Mismatch in css-flexbox-1.json: f=flex_context s=align-content
  Mismatch in css-flexbox-1.json: f=grid_context s=align-content
  Mismatch in css-flexbox-1.json: f=flex_context s=align-items
  Mismatch in css-flexbox-1.json: f=grid_context s=align-items
  Mismatch in css-flexbox-1.json: f=flex_context s=align-self
  Mismatch in css-flexbox-1.json: f=grid_context s=align-self
  Mismatch in css-flexbox-1.json: f=flex_context s=justify-content
  Mismatch in css-flexbox-1.json: f=grid_context s=justify-content
css-flexbox-1.json total: 8
  Mismatch in css-fonts-3.json: f=font-face s=@font-face
css-fonts-3.json total: 1
  Mismatch in css-fonts-4.json: f=font-feature-values s=@font-feature-values
css-fonts-4.json total: 1
  Mismatch in css-grid-1.json: f=flex_context s=column-gap
  Mismatch in css-grid-1.json: f=grid_context s=column-gap
  Mismatch in css-grid-1.json: f=multicol_context s=column-gap
  Mismatch in css-grid-1.json: f=animation s=grid-template-columns
  Mismatch in css-grid-1.json: f=animation s=grid-template-rows
  Mismatch in css-grid-1.json: f=flex s=flex_value
css-grid-1.json total: 6
  Mismatch in css-grid-2.json: f=animation s=grid-template-columns
  Mismatch in css-grid-2.json: f=animation s=grid-template-rows
css-grid-2.json total: 2
  Mismatch in css-images-3.json: f=gradients s=gradient
css-images-3.json total: 1
  Mismatch in css-images-4.json: f=gradients s=gradient
  Mismatch in css-images-4.json: f=image s=imagefunction
css-images-4.json total: 2
  Mismatch in css-lists-3.json: f=marker s=::marker
css-lists-3.json total: 1
  Mismatch in css-logical-1.json: f=page-margin-boxes s=@page
  Mismatch in css-logical-1.json: f=page s=@page
css-logical-1.json total: 2
  Mismatch in css-mediaqueries-3.json: f=import s=@import
  Mismatch in css-mediaqueries-3.json: f=media s=@media
css-mediaqueries-3.json total: 2
  Mismatch in css-multicol-1.json: f=multicol_context s=break-after
  Mismatch in css-multicol-1.json: f=paged_context s=break-after
  Mismatch in css-multicol-1.json: f=region_context s=break-after
  Mismatch in css-multicol-1.json: f=multicol_context s=break-before
  Mismatch in css-multicol-1.json: f=paged_context s=break-before
  Mismatch in css-multicol-1.json: f=region_context s=break-before
  Mismatch in css-multicol-1.json: f=multicol_context s=break-inside
  Mismatch in css-multicol-1.json: f=paged_context s=break-inside
  Mismatch in css-multicol-1.json: f=region_context s=break-inside
  Mismatch in css-multicol-1.json: f=flex_context s=column-gap
  Mismatch in css-multicol-1.json: f=grid_context s=column-gap
  Mismatch in css-multicol-1.json: f=multicol_context s=column-gap
css-multicol-1.json total: 12
  Mismatch in css-namespaces-3.json: f=namespace s=@namespace
  Mismatch in css-namespaces-3.json: f=namespace s=@namespace
css-namespaces-3.json total: 2
  Mismatch in css-page-3.json: f=page-margin-boxes s=@page
  Mismatch in css-page-3.json: f=page s=@page
  Mismatch in css-page-3.json: f=first s=:first
  Mismatch in css-page-3.json: f=left s=:left
  Mismatch in css-page-3.json: f=right s=:right
css-page-3.json total: 5
  Mismatch in css-paint-api-1.json: f=PaintWorkletGlobalScope s=PaintWorklet
css-paint-api-1.json total: 1
  Mismatch in css-pseudo-4.json: f=after s=::after
  Mismatch in css-pseudo-4.json: f=before s=::before
  Mismatch in css-pseudo-4.json: f=first-letter s=::first-letter
  Mismatch in css-pseudo-4.json: f=first-line s=::first-line
  Mismatch in css-pseudo-4.json: f=grammar-error s=::grammar-error
  Mismatch in css-pseudo-4.json: f=marker s=::marker
  Mismatch in css-pseudo-4.json: f=placeholder s=::placeholder
  Mismatch in css-pseudo-4.json: f=selection s=::selection
  Mismatch in css-pseudo-4.json: f=spelling-error s=::spelling-error
css-pseudo-4.json total: 9
  Mismatch in css-regions-1.json: f=multicol_context s=break-after
  Mismatch in css-regions-1.json: f=paged_context s=break-after
  Mismatch in css-regions-1.json: f=region_context s=break-after
  Mismatch in css-regions-1.json: f=multicol_context s=break-before
  Mismatch in css-regions-1.json: f=paged_context s=break-before
  Mismatch in css-regions-1.json: f=region_context s=break-before
  Mismatch in css-regions-1.json: f=multicol_context s=break-inside
  Mismatch in css-regions-1.json: f=paged_context s=break-inside
  Mismatch in css-regions-1.json: f=region_context s=break-inside
css-regions-1.json total: 9
  Mismatch in css-round-display-1.json: f=viewport s=@viewport
css-round-display-1.json total: 1
  Mismatch in css-scoping-1.json: f=host-context s=:host-context()
  Mismatch in css-scoping-1.json: f=host s=:host
  Mismatch in css-scoping-1.json: f=hostfunction s=:host()
  Mismatch in css-scoping-1.json: f=slotted s=::slotted
css-scoping-1.json total: 4
  Mismatch in css-shadow-parts-1.json: f=part s=::part
css-shadow-parts-1.json total: 1
  Mismatch in css-text-3.json: f=word-wrap s=overflow-wrap
css-text-3.json total: 1
  Mismatch in css-text-decor-3.json: f=first-letter s=::first-letter
  Mismatch in css-text-decor-3.json: f=first-line s=::first-line
css-text-decor-3.json total: 2
  Mismatch in css-values-3.json: f=position s=position_value
css-values-3.json total: 1
  Mismatch in css-variables-1.json: f=custom-property s=--*
css-variables-1.json total: 1
  Mismatch in ecmascript.json: f=classes s=Classes
  Mismatch in ecmascript.json: f=arrow_functions s=Arrow_functions
  Mismatch in ecmascript.json: f=default_parameters s=Default_parameters
  Mismatch in ecmascript.json: f=functions s=Functions
  Mismatch in ecmascript.json: f=method_definitions s=Method_definitions
  Mismatch in ecmascript.json: f=template_literals s=Template_literals
  Mismatch in ecmascript.json: f=async_function_expression s=async_function
  Mismatch in ecmascript.json: f=comma s=Comma_operator
  Mismatch in ecmascript.json: f=conditional s=Conditional_Operator
  Mismatch in ecmascript.json: f=destructuring s=Destructuring_assignment
  Mismatch in ecmascript.json: f=function_star s=function*
  Mismatch in ecmascript.json: f=generator_function s=function*
  Mismatch in ecmascript.json: f=grouping s=Grouping
  Mismatch in ecmascript.json: f=new_target s=new.target
  Mismatch in ecmascript.json: f=object_initializer s=Object_initializer
  Mismatch in ecmascript.json: f=property_accessors s=Property_Accessors
  Mismatch in ecmascript.json: f=yield_star s=yield*
  Mismatch in ecmascript.json: f=switch s=default
  Mismatch in ecmascript.json: f=export s=default
  Mismatch in ecmascript.json: f=do_while s=do...while
  Mismatch in ecmascript.json: f=empty s=Empty
  Mismatch in ecmascript.json: f=for_await_of s=for-await...of
  Mismatch in ecmascript.json: f=for_in s=for...in
  Mismatch in ecmascript.json: f=for_of s=for...of
  Mismatch in ecmascript.json: f=if_else s=if...else
  Mismatch in ecmascript.json: f=try_catch s=try...catch
ecmascript.json total: 26
  Mismatch in fullscreen.json: f=backdrop s=::backdrop
  Mismatch in fullscreen.json: f=fullscreen s=:fullscreen
fullscreen.json total: 2
  Mismatch in hr-time-1.json: f=DOMHighResTimestamp s=DOMHighResTimeStamp
hr-time-1.json total: 1
  Mismatch in hr-time-2.json: f=DOMHighResTimestamp s=DOMHighResTimeStamp
hr-time-2.json total: 1
  Mismatch in html-media-capture.json: f=input-file s=file
html-media-capture.json total: 1
  Mismatch in html.json: f=active s=:active
  Mismatch in html.json: f=checked s=:checked
  Mismatch in html.json: f=default s=:default
  Mismatch in html.json: f=defined s=:defined
  Mismatch in html.json: f=dir s=:dir
  Mismatch in html.json: f=disabled s=:disabled
  Mismatch in html.json: f=enabled s=:enabled
  Mismatch in html.json: f=focus s=:focus
  Mismatch in html.json: f=hover s=:hover
  Mismatch in html.json: f=in-range s=:in-range
  Mismatch in html.json: f=indeterminate s=:indeterminate
  Mismatch in html.json: f=invalid s=:invalid
  Mismatch in html.json: f=link s=:link
  Mismatch in html.json: f=optional s=:optional
  Mismatch in html.json: f=out-of-range s=:out-of-range
  Mismatch in html.json: f=read-only s=:read-only
  Mismatch in html.json: f=read-write s=:read-write
  Mismatch in html.json: f=required s=:required
  Mismatch in html.json: f=target s=:target
  Mismatch in html.json: f=valid s=:valid
  Mismatch in html.json: f=visited s=:visited
  Mismatch in html.json: f=h1 s=Heading_Elements
  Mismatch in html.json: f=h2 s=Heading_Elements
  Mismatch in html.json: f=h3 s=Heading_Elements
  Mismatch in html.json: f=h4 s=Heading_Elements
  Mismatch in html.json: f=h5 s=Heading_Elements
  Mismatch in html.json: f=h6 s=Heading_Elements
  Mismatch in html.json: f=input-button s=button
  Mismatch in html.json: f=input-checkbox s=checkbox
  Mismatch in html.json: f=input-color s=color
  Mismatch in html.json: f=input-date s=date
  Mismatch in html.json: f=input-datetime-local s=datetime-local
  Mismatch in html.json: f=input-email s=email
  Mismatch in html.json: f=input-file s=file
  Mismatch in html.json: f=input-hidden s=hidden
  Mismatch in html.json: f=input-image s=image
  Mismatch in html.json: f=input-month s=month
  Mismatch in html.json: f=input-number s=number
  Mismatch in html.json: f=input-password s=password
  Mismatch in html.json: f=input-radio s=radio
  Mismatch in html.json: f=input-range s=range
  Mismatch in html.json: f=input-reset s=reset
  Mismatch in html.json: f=input-search s=search
  Mismatch in html.json: f=input-text s=text
  Mismatch in html.json: f=input-submit s=submit
  Mismatch in html.json: f=input-tel s=tel
  Mismatch in html.json: f=input-time s=time
  Mismatch in html.json: f=input-url s=url
  Mismatch in html.json: f=input-week s=week
  Mismatch in html.json: f=data_attributes s=data-*
  Mismatch in html.json: f=import_meta s=import.meta
html.json total: 51
  Mismatch in mediaqueries-4.json: f=update s=update-frequency
  Mismatch in mediaqueries-4.json: f=media s=@media
mediaqueries-4.json total: 2
  Mismatch in mediaqueries-5.json: f=media s=@media
mediaqueries-5.json total: 1
  Mismatch in notifications.json: f=actions s=showNotification
  Mismatch in notifications.json: f=badge s=showNotification
  Mismatch in notifications.json: f=data s=showNotification
  Mismatch in notifications.json: f=image s=showNotification
  Mismatch in notifications.json: f=renotify s=showNotification
  Mismatch in notifications.json: f=requireInteraction s=showNotification
  Mismatch in notifications.json: f=vibrate s=showNotification
notifications.json total: 7
  Mismatch in proposal-class-fields.json: f=private_class_fields s=Class_elements
  Mismatch in proposal-class-fields.json: f=public_class_fields s=Class_elements
  Mismatch in proposal-class-fields.json: f=static_class_fields s=Class_fields
proposal-class-fields.json total: 3
  Mismatch in proposal-import-meta.json: f=import_meta s=import.meta
proposal-import-meta.json total: 1
  Mismatch in proposal-nullish-coalescing.json: f=nullish_coalescing s=Nullish_coalescing_operator
proposal-nullish-coalescing.json total: 1
  Mismatch in proposal-optional-chaining.json: f=optional_chaining s=Optional_chaining
proposal-optional-chaining.json total: 1
  Mismatch in proposal-pipeline-operator.json: f=pipeline s=Pipeline_operator
proposal-pipeline-operator.json total: 1
  Mismatch in selection-api.json: f=setPosition s=collapse
  Mismatch in selection-api.json: f=empty s=removeAllRanges
selection-api.json total: 2
  Mismatch in selectors-3.json: f=active s=:active
  Mismatch in selectors-3.json: f=adjacent_sibling s=Adjacent_sibling_combinator
  Mismatch in selectors-3.json: f=after s=::after
  Mismatch in selectors-3.json: f=before s=::before
  Mismatch in selectors-3.json: f=attribute s=Attribute_selectors
  Mismatch in selectors-3.json: f=checked s=:checked
  Mismatch in selectors-3.json: f=child s=Child_combinator
  Mismatch in selectors-3.json: f=class s=Class_selectors
  Mismatch in selectors-3.json: f=descendant s=Descendant_combinator
  Mismatch in selectors-3.json: f=disabled s=:disabled
  Mismatch in selectors-3.json: f=enabled s=:enabled
  Mismatch in selectors-3.json: f=empty s=:empty
  Mismatch in selectors-3.json: f=first-child s=:first-child
  Mismatch in selectors-3.json: f=first-letter s=::first-letter
  Mismatch in selectors-3.json: f=first-line s=::first-line
  Mismatch in selectors-3.json: f=first-of-type s=:first-of-type
  Mismatch in selectors-3.json: f=focus s=:focus
  Mismatch in selectors-3.json: f=hover s=:hover
  Mismatch in selectors-3.json: f=general_sibling s=General_sibling_combinator
  Mismatch in selectors-3.json: f=id s=ID_selectors
  Mismatch in selectors-3.json: f=lang s=:lang
  Mismatch in selectors-3.json: f=last-child s=:last-child
  Mismatch in selectors-3.json: f=last-of-type s=:last-of-type
  Mismatch in selectors-3.json: f=link s=:link
  Mismatch in selectors-3.json: f=visited s=:visited
  Mismatch in selectors-3.json: f=not s=:not
  Mismatch in selectors-3.json: f=nth-child s=:nth-child
  Mismatch in selectors-3.json: f=nth-last-child s=:nth-last-child
  Mismatch in selectors-3.json: f=nth-last-of-type s=:nth-last-of-type
  Mismatch in selectors-3.json: f=nth-of-type s=:nth-of-type
  Mismatch in selectors-3.json: f=only-child s=:only-child
  Mismatch in selectors-3.json: f=only-of-type s=:only-of-type
  Mismatch in selectors-3.json: f=root s=:root
  Mismatch in selectors-3.json: f=target s=:target
  Mismatch in selectors-3.json: f=type s=Type_selectors
  Mismatch in selectors-3.json: f=universal s=Universal_selectors
selectors-3.json total: 36
  Mismatch in selectors-4.json: f=-moz-ui-invalid s=:-moz-ui-invalid
  Mismatch in selectors-4.json: f=active s=:active
  Mismatch in selectors-4.json: f=adjacent_sibling s=Adjacent_sibling_combinator
  Mismatch in selectors-4.json: f=any-link s=:any-link
  Mismatch in selectors-4.json: f=attribute s=Attribute_selectors
  Mismatch in selectors-4.json: f=blank s=:blank
  Mismatch in selectors-4.json: f=checked s=:checked
  Mismatch in selectors-4.json: f=child s=Child_combinator
  Mismatch in selectors-4.json: f=class s=Class_selectors
  Mismatch in selectors-4.json: f=column s=Column_combinator
  Mismatch in selectors-4.json: f=default s=:default
  Mismatch in selectors-4.json: f=descendant s=Descendant_combinator
  Mismatch in selectors-4.json: f=dir s=:dir
  Mismatch in selectors-4.json: f=disabled s=:disabled
  Mismatch in selectors-4.json: f=enabled s=:enabled
  Mismatch in selectors-4.json: f=empty s=:empty
  Mismatch in selectors-4.json: f=first-child s=:first-child
  Mismatch in selectors-4.json: f=first-of-type s=:first-of-type
  Mismatch in selectors-4.json: f=focus-visible s=:focus-visible
  Mismatch in selectors-4.json: f=focus-within s=:focus-within
  Mismatch in selectors-4.json: f=focus s=:focus
  Mismatch in selectors-4.json: f=general_sibling s=General_sibling_combinator
  Mismatch in selectors-4.json: f=has s=:has
  Mismatch in selectors-4.json: f=hover s=:hover
  Mismatch in selectors-4.json: f=id s=ID_selectors
  Mismatch in selectors-4.json: f=in-range s=:in-range
  Mismatch in selectors-4.json: f=indeterminate s=:indeterminate
  Mismatch in selectors-4.json: f=invalid s=:invalid
  Mismatch in selectors-4.json: f=valid s=:valid
  Mismatch in selectors-4.json: f=is s=:is
  Mismatch in selectors-4.json: f=lang s=:lang
  Mismatch in selectors-4.json: f=last-child s=:last-child
  Mismatch in selectors-4.json: f=last-of-type s=:last-of-type
  Mismatch in selectors-4.json: f=link s=:link
  Mismatch in selectors-4.json: f=visited s=:visited
  Mismatch in selectors-4.json: f=list s=Selector_list
  Mismatch in selectors-4.json: f=not s=:not
  Mismatch in selectors-4.json: f=nth-child s=:nth-child
  Mismatch in selectors-4.json: f=nth-last-child s=:nth-last-child
  Mismatch in selectors-4.json: f=nth-last-of-type s=:nth-last-of-type
  Mismatch in selectors-4.json: f=nth-of-type s=:nth-of-type
  Mismatch in selectors-4.json: f=only-child s=:only-child
  Mismatch in selectors-4.json: f=only-of-type s=:only-of-type
  Mismatch in selectors-4.json: f=optional s=:optional
  Mismatch in selectors-4.json: f=required s=:required
  Mismatch in selectors-4.json: f=out-of-range s=:out-of-range
  Mismatch in selectors-4.json: f=placeholder-shown s=:placeholder-shown
  Mismatch in selectors-4.json: f=read-only s=:read-only
  Mismatch in selectors-4.json: f=read-write s=:read-write
  Mismatch in selectors-4.json: f=root s=:root
  Mismatch in selectors-4.json: f=scope s=:scope
  Mismatch in selectors-4.json: f=target s=:target
  Mismatch in selectors-4.json: f=type s=Type_selectors
  Mismatch in selectors-4.json: f=universal s=Universal_selectors
selectors-4.json total: 54
  Mismatch in svg-2.json: f=data s=data-*
svg-2.json total: 1
  Mismatch in url.json: f=input-url s=url
url.json total: 1
  Mismatch in webcryptoapi.json: f=algorithm s=CryptoKey
  Mismatch in webcryptoapi.json: f=extractable s=CryptoKey
  Mismatch in webcryptoapi.json: f=type s=CryptoKey
  Mismatch in webcryptoapi.json: f=usages s=CryptoKey
webcryptoapi.json total: 4
  Mismatch in webgl-1.json: f=texParameterf s=texParameter
  Mismatch in webgl-1.json: f=texParameteri s=texParameter
  Mismatch in webgl-1.json: f=uniform1f s=uniform
  Mismatch in webgl-1.json: f=uniform1fv s=uniform
  Mismatch in webgl-1.json: f=uniform1i s=uniform
  Mismatch in webgl-1.json: f=uniform1iv s=uniform
  Mismatch in webgl-1.json: f=uniform2f s=uniform
  Mismatch in webgl-1.json: f=uniform2fv s=uniform
  Mismatch in webgl-1.json: f=uniform2i s=uniform
  Mismatch in webgl-1.json: f=uniform2iv s=uniform
  Mismatch in webgl-1.json: f=uniform3f s=uniform
  Mismatch in webgl-1.json: f=uniform3fv s=uniform
  Mismatch in webgl-1.json: f=uniform3i s=uniform
  Mismatch in webgl-1.json: f=uniform3iv s=uniform
  Mismatch in webgl-1.json: f=uniform4f s=uniform
  Mismatch in webgl-1.json: f=uniform4fv s=uniform
  Mismatch in webgl-1.json: f=uniform4i s=uniform
  Mismatch in webgl-1.json: f=uniform4iv s=uniform
  Mismatch in webgl-1.json: f=uniformMatrix2fv s=uniformMatrix
  Mismatch in webgl-1.json: f=uniformMatrix3fv s=uniformMatrix
  Mismatch in webgl-1.json: f=uniformMatrix4fv s=uniformMatrix
  Mismatch in webgl-1.json: f=vertexAttrib1f s=vertexAttrib
  Mismatch in webgl-1.json: f=vertexAttrib1fv s=vertexAttrib
  Mismatch in webgl-1.json: f=vertexAttrib2f s=vertexAttrib
  Mismatch in webgl-1.json: f=vertexAttrib2fv s=vertexAttrib
  Mismatch in webgl-1.json: f=vertexAttrib3f s=vertexAttrib
  Mismatch in webgl-1.json: f=vertexAttrib3fv s=vertexAttrib
  Mismatch in webgl-1.json: f=vertexAttrib4f s=vertexAttrib
  Mismatch in webgl-1.json: f=vertexAttrib4fv s=vertexAttrib
webgl-1.json total: 29
  Mismatch in webgl-2.json: f=clearBufferfi s=clearBuffer
  Mismatch in webgl-2.json: f=clearBufferfv s=clearBuffer
  Mismatch in webgl-2.json: f=clearBufferiv s=clearBuffer
  Mismatch in webgl-2.json: f=clearBufferuiv s=clearBuffer
  Mismatch in webgl-2.json: f=texParameterf s=texParameter
  Mismatch in webgl-2.json: f=texParameteri s=texParameter
  Mismatch in webgl-2.json: f=uniform1f s=uniform
  Mismatch in webgl-2.json: f=uniform1i s=uniform
  Mismatch in webgl-2.json: f=uniform1ui s=uniform
  Mismatch in webgl-2.json: f=uniform1uiv s=uniform
  Mismatch in webgl-2.json: f=uniform2f s=uniform
  Mismatch in webgl-2.json: f=uniform2i s=uniform
  Mismatch in webgl-2.json: f=uniform2ui s=uniform
  Mismatch in webgl-2.json: f=uniform2uiv s=uniform
  Mismatch in webgl-2.json: f=uniform3f s=uniform
  Mismatch in webgl-2.json: f=uniform3i s=uniform
  Mismatch in webgl-2.json: f=uniform3ui s=uniform
  Mismatch in webgl-2.json: f=uniform3uiv s=uniform
  Mismatch in webgl-2.json: f=uniform4f s=uniform
  Mismatch in webgl-2.json: f=uniform4i s=uniform
  Mismatch in webgl-2.json: f=uniform4ui s=uniform
  Mismatch in webgl-2.json: f=uniform4uiv s=uniform
  Mismatch in webgl-2.json: f=uniformMatrix2fv s=uniformMatrix
  Mismatch in webgl-2.json: f=uniformMatrix2x3fv s=uniformMatrix
  Mismatch in webgl-2.json: f=uniformMatrix2x4fv s=uniformMatrix
  Mismatch in webgl-2.json: f=uniformMatrix3fv s=uniformMatrix
  Mismatch in webgl-2.json: f=uniformMatrix3x2fv s=uniformMatrix
  Mismatch in webgl-2.json: f=uniformMatrix3x4fv s=uniformMatrix
  Mismatch in webgl-2.json: f=uniformMatrix4fv s=uniformMatrix
  Mismatch in webgl-2.json: f=uniformMatrix4x2fv s=uniformMatrix
  Mismatch in webgl-2.json: f=uniformMatrix4x3fv s=uniformMatrix
  Mismatch in webgl-2.json: f=vertexAttribI4i s=vertexAttribI
  Mismatch in webgl-2.json: f=vertexAttribI4iv s=vertexAttribI
  Mismatch in webgl-2.json: f=vertexAttribI4ui s=vertexAttribI
  Mismatch in webgl-2.json: f=vertexAttribI4uiv s=vertexAttribI
webgl-2.json total: 35
  Mismatch in webvtt.json: f=cue s=::cue
webvtt.json total: 1
Total mismatches: 414 across 60 specs.
128 of the total were pseudo-class/elements.
24 of the total were input-related.
</pre>
</details>

I'll excerpt the concluding messages:

* Total mismatches: 414 across 60 specs.
* 128 of the total were pseudo-class/elements. (slug starts with ":")
* 24 of the total were input-related. (feature name starts with "input-")

Since we have about 250 specs in the database, this means that ~1/4 of all specs have at least one mismatch.

A quick look over them shows that mismatches occur for a *variety* of reasons. For example, a CSS property that is interpreted differently in various layouts will typically have one MDN url, but different features names with the pattern `flex_context`, etc.  A lot of them are just slightly different wording: a feature name of `position` but a slug of `position_value`.  And another big group are multiple distinct features that share a single MDN page: all the mistmatches in notification.json are from the various arguments to the `showNotification()` method all linking to the single `showNotification` url.

So, putting together exceptions for the allowed mismatches would be a bit of work. Might still be worth it, tho.

----

I did notice several that are just down to casing differences, which should be trivial to just fix, tho. When I get time I'll deliver them.

**Comment by sideshowbarker** [comment]
> I was composing an issue against BCD for this, and tracked down the full list of mismatches:

Thanks for generating this list

> putting together exceptions for the allowed mismatches would be a bit of work.

Yeah, I’ve been looking through the list and trying to figure out how to approach it, but as you’ve noted, the exceptions fall into a number of different classes.

Anyway, I’m gonna spend some more time on this. I think some simple refinements to the original check — like handling the leading `:` characters — will reduce the list a lot. Then, as far as the cases that really don’t lend themselves to an automated check, those can just be into hard-coded accept list. So that could be used as the basis for the initial linter for BCD, and then if/when we get a patch from a PR that fails the lint due to a false positive, it could just be added to the accept list as a part of the same PR.
