### ISSUE TITLE
Lots of specs in specmap missing in the actual repo

### ISSUE THREAD

**Issue by tabatkins** [w3c/mdn-spec-links#8]
A *lot* of specs present in `SPECMAP.json` are missing from the actual repository. For example, the specmap lists both `css-values-3.json` and `css-values-4.json`, but both are missing (only `css-values.json` exists).

This is causing fatal errors in Bikeshed specs :(

**Comment by sideshowbarker** [comment]
Sorry, will fix it asap, and ping you as soon as I've got it fixed.

**Comment by tabatkins** [comment]
It'll auto-fix itself the next time bikeshed-data polls, so no need to ping me. Thanks!
